# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'

- task: Docker@2
  inputs:
    containerRegistry: 'DockerHubConnection'
    repository: 'reptilianusbileciktus/website'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'