apiVersion: v1
kind: Service
metadata:
  name: website-svc
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: website-deployment-7f8f9f7857-xph9f
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080